### ISSUE TITLE
Can you please provide that Stackoverflow dataset?

### ISSUE THREAD

**Issue by tactical-khojee** [chinyan/Retrieval-based-Chatbot-for-Q-A#1]

**Comment by chinyan** [comment]
Please find the Question and Answer pair in the CSV file below:
https://www.dropbox.com/s/2vxxxckkfwvfcfq/StackOverflow.csv?dl=0

**Comment by tactical-khojee** [comment]
Thank You!


Sincerely,
Aditya Kakliya
