### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './Data/StackOverflow_Word2Vec.json'

### ISSUE THREAD

**Issue by SimplifyOrg** [chinyan/Retrieval-based-Chatbot-for-Q-A#2]
I am getting this error when I select a language from the HTML UI. It seems ./Data/StackOverflow_Word2Vec.json' is missing from the repository. It would be great if you could share the file or let me know how can I create it.

Thanks!

**Comment by rishabhchauhan9760** [comment]
hey where is the stackoverflow .csv file

**Comment by chinyan** [comment]
> hey where is the stackoverflow .csv file

Please find the Question and Answer pair in the CSV file below:
https://www.dropbox.com/s/2vxxxckkfwvfcfq/StackOverflow.csv?dl=0

**Comment by chinyan** [comment]
> I am getting this error when I select a language from the HTML UI. It seems ./Data/StackOverflow_Word2Vec.json' is missing from the repository. It would be great if you could share the file or let me know how can I create it.
> 
> Thanks!

@SimplifyOrg you first have to run through the Jupyter Notebook to generate the respective JSON files found in './Data/StackOverflow_Word2Vec.ipynb'

**Comment by chinyan** [comment]
@SimplifyOrg @rishabhchauhan9760 
Please follow the following steps:
1. Ensure the CSV file, 'StackOverflow.csv', has been downloaded into the './Data/' folder. The download link is: https://www.dropbox.com/s/2vxxxckkfwvfcfq/StackOverflow.csv?dl=0
2. Exectue each cell in the Jupyter Notebook, './Data/StackOverflow_Word2Vec.ipynb', to generate the respective JSON files.
3. Run chatbot.py to start UI.
4. Go to any web browser and type http://localhost:8000/
